# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from otherwindow import Ui_OtherWindow

class Ui_MainWindow(object):
    # def openWindow(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = Ui_OtherWindow()
    #     self.ui.setupUi(self.window)
    #     self.window.show()
    #     self.ui.OtherWindow.setText(str("test"))

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(478, 761)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #22222e")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 480, 321))
        self.frame.setStyleSheet("background-color: #EDDACC")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 10, 351, 121))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(72)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #90816A")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(150, 130, 181, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("python.png"))
        self.label_2.setObjectName("label_2")
        self.btn_open = QtWidgets.QPushButton(self.frame)
        self.btn_open.setGeometry(QtCore.QRect(150, 140, 181, 161))
        self.btn_open.setStyleSheet("QPushButton:pressed {\n"
"    background-color:transparent\n"
"}")
        self.btn_open.setText("")
        self.btn_open.setAutoDefault(False)
        self.btn_open.setDefault(False)
        self.btn_open.setFlat(True)
        self.btn_open.setObjectName("btn_open")

        # self.btn_open.clicked.connect(self.openWindow)

        self.input_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.input_amount.setGeometry(QtCore.QRect(50, 420, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input_amount.setFont(font)
        self.input_amount.setStyleSheet("color: #EDDACC;\n"
"border: 2px solid #EDDACC;\n"
"border-radius: 30px;\n"
"color: #90816A\n"
"")
        self.input_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.input_amount.setObjectName("input_amount")
        self.outpuy_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.outpuy_amount.setGeometry(QtCore.QRect(50, 580, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.outpuy_amount.setFont(font)
        self.outpuy_amount.setStyleSheet("color: #EDDACC;\n"
"border: 2px solid #EDDACC;\n"
"border-radius: 30px;\n"
"color: #90816A\n"
"")
        self.outpuy_amount.setAlignment(QtCore.Qt.AlignCenter)
        self.outpuy_amount.setObjectName("outpuy_amount")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 670, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    color: #90816A ;\n"
"    background-color: #EDDACC ;\n"
"    border-radius: 30;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:#D69E8F\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(50, 340, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("color: #EDDACC;\n"
"border: 2px solid #EDDACC;\n"
"border-radius: 30px;\n"
"color: #90816A\n"
"")
        self.comboBox.setInputMethodHints(QtCore.Qt.ImhNone)
        self.comboBox.setEditable(False)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(50, 500, 380, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setStyleSheet("color: #EDDACC;\n"
"border: 2px solid #EDDACC;\n"
"border-radius: 30px;\n"
"color: #90816A\n"
"")
        self.comboBox_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "converter"))
        self.input_amount.setText(_translate("MainWindow", "1"))
        self.outpuy_amount.setText(_translate("MainWindow", "1"))
        self.pushButton.setText(_translate("MainWindow", "CONVERT"))
        self.comboBox.setItemText(0, _translate("MainWindow", "USD"))
        self.comboBox.setItemText(1, _translate("MainWindow", "EUR"))
        self.comboBox.setItemText(2, _translate("MainWindow", "RUB"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "USD"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "EUR"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "RUB"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
